plugins {
	id 'net.fabricmc.fabric-loom' version "${loom_version}"
	id 'maven-publish'
}

def mcSuffix = project.minecraft_version.tokenize('.').take(2).join('.')
def mcNext = "${mcSuffix.tokenize('.')[0]}.${(mcSuffix.tokenize('.')[1] as int) + 1}"
version = "${project.mod_version}+${mcSuffix}"
group = project.maven_group

base {
	archivesName = project.archives_base_name
}

fabricApi {
	configureDataGeneration {
		client = true
		modId = "verdance"
		outputDirectory = rootProject.file("src/generated/resources")
	}
}

repositories {
	maven {
		name = "NeoForge"
		url = uri("https://maven.neoforged.net/releases/")
		content {
			includeGroupAndSubgroups("net.neoforged")
			includeGroupAndSubgroups("cpw.mods")
			includeGroupAndSubgroups("dev.yumi")
		}
	}
	maven { url = "https://api.modrinth.com/maven" }
}

sourceSets {
	main {
		java.srcDirs = [rootProject.file("src/main/java")]
		resources.srcDirs = [rootProject.file("src/main/resources"), rootProject.file("src/generated/resources")]
	}
	fabric {
		java.srcDirs = [rootProject.file("src/fabric/java")]
		resources.srcDirs = [rootProject.file("src/fabric/resources")]
		compileClasspath += main.compileClasspath
		runtimeClasspath += main.runtimeClasspath
	}
	neoforge {
		java.srcDirs = [rootProject.file("src/neoforge/java")]
		resources.srcDirs = [rootProject.file("src/neoforge/resources")]
		compileClasspath += main.compileClasspath
		runtimeClasspath += main.runtimeClasspath
	}
}

if (mcSuffix == "26.2") {
	sourceSets.fabric.java.exclude("com/teamabode/verdance/datagen/**")
}

loom {
	accessWidenerPath = rootProject.file("src/main/resources/verdance.classtweaker")

	runs {
		datagen {
			client()
			name "Data Generation"
			vmArg "-Dfabric-api.datagen"
			vmArg "-Dfabric-api.datagen.output-dir=${rootProject.file("src/generated/resources")}"
			vmArg "-Dfabric-api.datagen.modid=verdance"

			runDir "build/datagen"
			source sourceSets.fabric
		}
	}
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"

	api include("dev.yumi.mc.core:yumi-mc-foundation:${project.yumi_version}")
	implementation("dev.yumi.mc.core:yumi-mc-foundation:${project.yumi_version}")

	compileOnly localRuntime("net.fabricmc:fabric-loader:${project.loader_version}")

	fabricCompileOnly localRuntime("net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}")

	neoforgeCompileOnly("net.neoforged:neoforge:${project.neoforge_version}:universal")
	neoforgeCompileOnly("net.neoforged.fancymodloader:loader:${project.neoforge_loader_version}")

	neoforgeImplementation sourceSets.main.output
	fabricImplementation sourceSets.main.output

	localRuntime sourceSets.fabric.output
}

def resourceTargets = ["fabric.mod.json", "META-INF/neoforge.mods.toml", "META-INF/jarjar/metadata.json"]
def replaceProperties = [
		"version": project.version, "yumi_version": project.yumi_version,
		"mc_major": mcSuffix, "mc_next": mcNext
]

processResources {
	inputs.properties replaceProperties
	duplicatesStrategy = DuplicatesStrategy.INCLUDE

	filesMatching(resourceTargets) {
		expand replaceProperties
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.encoding = "UTF-8"
	it.options.release = 25
}

tasks.withType(Jar).configureEach {
	duplicatesStrategy = DuplicatesStrategy.INCLUDE
}

java {
	withSourcesJar()

	sourceCompatibility = JavaVersion.VERSION_25
	targetCompatibility = JavaVersion.VERSION_25
}

jar {
	from(rootProject.file("LICENSE")) {
		rename { "${it}_${project.archives_base_name}" }
	}

	from(sourceSets.neoforge.output)
	from(sourceSets.fabric.output) {
		exclude "com/teamabode/verdance/datagen/**"
	}
}

sourcesJar {
	from(sourceSets.neoforge.java.sourceDirectories)
	from(sourceSets.neoforge.resources.sourceDirectories)
	from(sourceSets.fabric.java.sourceDirectories)
	from(sourceSets.fabric.resources.sourceDirectories)
}

publishing {
	publications {
		create("mavenJava", MavenPublication) {
			artifactId = project.archives_base_name
			from components.java
		}
	}
	repositories {
		mavenLocal()
	}
}
