modLoader = "javafml"
loaderVersion = "[2,)"
license = "All Rights Reserved"
issueTrackerURL = "https://github.com/digi2303/verdance/issues"

[[mods]]
	modId = "verdance"
	version = "${version}"
	displayName = "Verdance"
	displayURL = "https://github.com/digi2303/verdance"
	description = "Adds mulberry trees, silk moths, and assorted natural decoration."
	authors = "Team Abode"
	logoFile = "assets/verdance/icon.png"
	logoBlur = false

[[accessTransformers]]
	file = "META-INF/accesstransformer.cfg"

[[mixins]]
	config = "verdance.mixins.json"

[[mixins]]
	config = "verdance.neo.mixins.json"

[[dependencies.verdance]]
	modId = "minecraft"
	type = "required"
	versionRange = "[${mc_major},${mc_next})"
	ordering = "NONE"
	side = "BOTH"

[[dependencies.verdance]]
	modId = "yumi_mc_core"
	type = "required"
	versionRange = "[${yumi_version},)"
	ordering = "NONE"
	side = "BOTH"

[[modproperties.verdance."yumi:entrypoints"."yumi:init"]]
	value = "com.teamabode.verdance.impl.VerdanceMain"

[[modproperties.verdance."yumi:entrypoints"."yumi:client_init"]]
	value = "com.teamabode.verdance.impl.client.VerdanceClient"
